/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Barang;

/**
 *
 * @author Lenovo-PC
 */
public class FrameBarang extends javax.swing.JFrame {

    /**
     * Creates new form FrameBarang
     */
    public FrameBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInputBarang = new javax.swing.JLabel();
        jLabelNamaBarang = new javax.swing.JLabel();
        jLabelHargaJual = new javax.swing.JLabel();
        jLabelHargaBeli = new javax.swing.JLabel();
        jLabelStok = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNamaBarang = new javax.swing.JTextField();
        jTextFieldHargaJual = new javax.swing.JTextField();
        jTextFieldHargaBeli = new javax.swing.JTextField();
        jTextFieldStok = new javax.swing.JTextField();
        jTextFieldExpired = new javax.swing.JTextField();
        jButtonAddBarang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelInputBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInputBarang.setText("Form Input Data Barang");

        jLabelNamaBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNamaBarang.setText("Nama Barang");

        jLabelHargaJual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelHargaJual.setText("Harga Jual");

        jLabelHargaBeli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelHargaBeli.setText("Harga Beli");

        jLabelStok.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelStok.setText("Stok");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Expired");

        jTextFieldNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaBarangActionPerformed(evt);
            }
        });

        jTextFieldHargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaJualActionPerformed(evt);
            }
        });

        jButtonAddBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAddBarang.setText("Add");
        jButtonAddBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNamaBarang)
                    .addComponent(jLabelHargaJual)
                    .addComponent(jLabelHargaBeli)
                    .addComponent(jLabelStok)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelInputBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNamaBarang)
                    .addComponent(jTextFieldHargaJual)
                    .addComponent(jTextFieldHargaBeli)
                    .addComponent(jTextFieldStok)
                    .addComponent(jTextFieldExpired))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddBarang)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInputBarang)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamaBarang)
                    .addComponent(jTextFieldNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHargaJual)
                    .addComponent(jTextFieldHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHargaBeli)
                    .addComponent(jTextFieldHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStok)
                    .addComponent(jTextFieldStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldExpired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAddBarang)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaBarangActionPerformed

    private void jButtonAddBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBarangActionPerformed
        // TODO add your handling code here:
        
        String nama_barang = jTextFieldNamaBarang.getText();
        int harga_jual = Integer.parseInt(jTextFieldHargaJual.getText());
        int harga_beli = Integer.parseInt(jTextFieldHargaBeli.getText());
        int stok = Integer.parseInt(jTextFieldStok.getText());
        String expired = jTextFieldExpired.getText();
        
        Barang b = new Barang(nama_barang, harga_beli, harga_jual, expired, stok);
        try {
            b.masukkanData();
            //System.out.println("Data Berhasil di Input!");
            JOptionPane.showMessageDialog(null, "Data Berhasil di Input!");
        } catch (Exception ex) {
            //Logger.getLogger(FrameBarang.class.getName()).log(Level.SEVERE, null, ex);
            //System.out.println("Data Tidak Berhasil di Input!");
            JOptionPane.showMessageDialog(null, "Data Tidak Berhasil di Input!");
        }
    }//GEN-LAST:event_jButtonAddBarangActionPerformed

    private void jTextFieldHargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaJualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHargaBeli;
    private javax.swing.JLabel jLabelHargaJual;
    private javax.swing.JLabel jLabelInputBarang;
    private javax.swing.JLabel jLabelNamaBarang;
    private javax.swing.JLabel jLabelStok;
    private javax.swing.JTextField jTextFieldExpired;
    private javax.swing.JTextField jTextFieldHargaBeli;
    private javax.swing.JTextField jTextFieldHargaJual;
    private javax.swing.JTextField jTextFieldNamaBarang;
    private javax.swing.JTextField jTextFieldStok;
    // End of variables declaration//GEN-END:variables
}
