/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.KoneksiDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import javax.swing.table.DefaultTableModel;
import model.Barang;

/**
 *
 * @author Lenovo-PC
 */
public class FrameDataBarang extends javax.swing.JFrame {
    private DefaultTableModel model;
    Barang b = new Barang();
    /**
     * Creates new form FrameDataBarang
     */
    public FrameDataBarang() {
        initComponents();
        model = new DefaultTableModel();
        jTableBarang.setModel(model);
        model.addColumn("No");
        model.addColumn("Nama Barang");
        model.addColumn("Harga Jual");
        model.addColumn("Harga Beli");
        model.addColumn("Jumlah Stok");
        model.addColumn("Expired");
        
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDataBarang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBarang = new javax.swing.JTable();
        jButtonEditBarang = new javax.swing.JButton();
        jButtonDeleteBarang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelDataBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDataBarang.setText("Data Barang");

        jTableBarang.setAutoCreateRowSorter(true);
        jTableBarang.setForeground(new java.awt.Color(255, 255, 255));
        jTableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Barang", "Harga Jual", "Harga Beli", "Jumlah Stok", "Expired"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableBarang.setGridColor(new java.awt.Color(153, 153, 153));
        jTableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBarang);

        jButtonEditBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonEditBarang.setText("Edit");
        jButtonEditBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditBarangActionPerformed(evt);
            }
        });

        jButtonDeleteBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonDeleteBarang.setText("Delete");
        jButtonDeleteBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jButtonEditBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteBarang))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabelDataBarang))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDataBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditBarang)
                    .addComponent(jButtonDeleteBarang))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditBarangActionPerformed

    private void jButtonDeleteBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteBarangActionPerformed
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_jButtonDeleteBarangActionPerformed

    private void jTableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBarangMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTableBarangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteBarang;
    private javax.swing.JButton jButtonEditBarang;
    private javax.swing.JLabel jLabelDataBarang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBarang;
    // End of variables declaration//GEN-END:variables
    
    public void deleteData(){
       int pesan = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin?", "Delete Barang", OK_CANCEL_OPTION);
       if (pesan == JOptionPane.OK_OPTION){
           try{
               KoneksiDB db = new KoneksiDB();
               Connection conn = db.getConn();
               Statement stat = conn.createStatement();
               
               String sql = "DELETE FROM barang WHERE nama_barang = "+b.getNama_barang()+"";
               ResultSet res = stat.executeQuery(sql);
               PreparedStatement ps = conn.prepareStatement(sql);
               ps.executeUpdate();
               
               getData();
               JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
           } catch (Exception e){
               JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
           }
       }
    }
    
    public void getData(){
        try{
            KoneksiDB db = new KoneksiDB();
            Connection conn = db.getConn();
            Statement stat = conn.createStatement();
            String sql = "SELECT * FROM barang";
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()){
                Object[] obj = new Object[6];
                obj[0] = res.getString("id_barang");
                obj[1] = res.getString("nama_barang");
                obj[2] = res.getString("harga_beli");
                obj[3] = res.getString("harga_jual");
                obj[4] = res.getString("expired");
                obj[5] = res.getString("stok");
                
                model.addRow(obj);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal di Tampilkan!");
        }
    }
}