/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.Barang;
import model.Karyawan;
import model.Order;
import model.Supplier;

/**
 *
 * @author ybnun
 */
public class FrameOrder extends javax.swing.JFrame {

    /**
     * Creates new form FrameOrder
     */
    public FrameOrder() {
        initComponents();
    }
    
    public void tampilDataKombo() throws SQLException {
		ResultSet rs = null;
		Karyawan dm = new Karyawan();
		boolean status = false;
		
		try{
			rs = dm.isiDataKombo();
			while(rs.next()){
				comNamaKar.addItem(rs.getString(1));
			}
		}catch (Exception ex){
			Logger.getLogger(FrameOrder.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
    
    public void tampilDataKomboBar() throws SQLException {
		ResultSet rs = null;
		Barang brg = new Barang();
		boolean status = false;
		
		try{
			rs = brg.isiDataKombo();
			while(rs.next()){
				comNamaBar.addItem(rs.getString(1));
			}
		}catch (Exception ex){
			Logger.getLogger(FrameOrder.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
    
    public void tampilDataKomboSup() throws SQLException {
		ResultSet rs = null;
		Supplier sup = new Supplier();
		boolean status = false;
		
		try{
			rs = sup.isiDataKombo();
			while(rs.next()){
				comNamaSup.addItem(rs.getString(1));
			}
		}catch (Exception ex){
			Logger.getLogger(FrameOrder.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comNamaKar = new javax.swing.JComboBox();
        comNamaBar = new javax.swing.JComboBox();
        comNamaSup = new javax.swing.JComboBox();
        txtJumOr = new javax.swing.JTextField();
        btOrder = new javax.swing.JButton();
        txtNamaKar = new javax.swing.JTextField();
        txtNamaBar = new javax.swing.JTextField();
        txtNamaSup = new javax.swing.JTextField();
        btBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Form Order Barang");

        jLabel2.setText("Nama Karyawan");

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Nama Supplier");

        jLabel5.setText("Jumlah Order");

        comNamaKar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comNamaKarActionPerformed(evt);
            }
        });

        comNamaBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comNamaBarActionPerformed(evt);
            }
        });

        comNamaSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comNamaSupActionPerformed(evt);
            }
        });

        txtJumOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumOrActionPerformed(evt);
            }
        });

        btOrder.setText("Order");
        btOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrderActionPerformed(evt);
            }
        });

        txtNamaKar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaKarActionPerformed(evt);
            }
        });

        txtNamaBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBarActionPerformed(evt);
            }
        });

        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(22, 22, 22)
                                .addComponent(txtJumOr))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(comNamaSup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comNamaBar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comNamaKar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamaBar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNamaKar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtNamaSup))))))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btBack)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comNamaKar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaKar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comNamaBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comNamaSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtJumOr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btBack)
                .addContainerGap())
        );

        try{
            tampilDataKombo();
        }catch (SQLException ex){
            Logger.getLogger(FrameOrder.class.getName()).log(Level.SEVERE, null, ex);
        }

        jPanel1.add(comNamaKar);
        jPanel1.add(comNamaKar, new java.awt.GridBagConstraints());
        try{
            tampilDataKomboBar();
        }catch (SQLException ex){
            Logger.getLogger(FrameOrder.class.getName()).log(Level.SEVERE, null, ex);
        }

        jPanel1.add(comNamaBar);
        jPanel1.add(comNamaBar, new java.awt.GridBagConstraints());
        try{
            tampilDataKomboSup();
        }catch (SQLException ex){
            Logger.getLogger(FrameOrder.class.getName()).log(Level.SEVERE, null, ex);
        }

        jPanel1.add(comNamaSup);
        jPanel1.add(comNamaSup, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumOrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumOrActionPerformed

    private void comNamaKarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNamaKarActionPerformed
        // TODO add your handling code here:
        ResultSet rs = null;
        String x = (String)comNamaKar.getSelectedItem();

        
            Karyawan kar = new Karyawan();
            boolean status = false;

            try {
                rs = kar.lihatData(x);
                if (rs.next()) {
                    txtNamaKar.setText(rs.getString(2));

                } else {
                    //JOptionPane.showMessageDialog(this, "View Gagal", "Status", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(FrameOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_comNamaKarActionPerformed

    private void comNamaBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNamaBarActionPerformed
        // TODO add your handling code here:
        ResultSet rs = null;
        String x = (String)comNamaBar.getSelectedItem();

        
            Barang brg = new Barang();
            boolean status = false;

            try {
                rs = brg.lihatData(x);
                if (rs.next()) {
                    txtNamaBar.setText(rs.getString(2));

                } else {
                    //JOptionPane.showMessageDialog(this, "View Gagal", "Status", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(FrameOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_comNamaBarActionPerformed

    private void comNamaSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNamaSupActionPerformed
        // TODO add your handling code here:
        ResultSet rs = null;
        String x = (String)comNamaSup.getSelectedItem();

        
            Supplier sup = new Supplier();
            boolean status = false;

            try {
                rs = sup.lihatData(x);
                if (rs.next()) {
                    txtNamaSup.setText(rs.getString(2));

                } else {
                    //JOptionPane.showMessageDialog(this, "View Gagal", "Status", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(FrameOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_comNamaSupActionPerformed

    private void btOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrderActionPerformed
        // TODO add your handling code here:
        String a = (String)comNamaKar.getSelectedItem();
        String b = (String)comNamaBar.getSelectedItem();
        String c = (String)comNamaSup.getSelectedItem();
        String d = txtJumOr.getText();
        int jum = Integer.parseInt(d);
        int idK = Integer.parseInt(a);
        int idB = Integer.parseInt(b);
        int idS = Integer.parseInt(c);
        
        boolean status = false;
        try{
                Order or = new Order(idK,idB,idS,jum);
                status = or.masukkanData();
        } catch (SQLException ex) {
                Logger.getLogger(FrameOrder.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(status){
                JOptionPane.showMessageDialog(this, "Order Berhasil","status",JOptionPane.INFORMATION_MESSAGE);
                txtJumOr.setText("");
                txtNamaBar.setText("");
                txtNamaKar.setText("");
                txtNamaSup.setText("");
        }else{
                JOptionPane.showMessageDialog(this, "Order Gagal","status",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btOrderActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        FrameHome fh = new FrameHome();
        fh.setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    private void txtNamaKarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKarActionPerformed

    private void txtNamaBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btOrder;
    private javax.swing.JComboBox comNamaBar;
    private javax.swing.JComboBox comNamaKar;
    private javax.swing.JComboBox comNamaSup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtJumOr;
    private javax.swing.JTextField txtNamaBar;
    private javax.swing.JTextField txtNamaKar;
    private javax.swing.JTextField txtNamaSup;
    // End of variables declaration//GEN-END:variables
}
